---
deployment:
  tasks:
    - export DEPLOYPATH=/home/elysgohr/develop.elysian-beauty.org/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .output $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
    - /bin/cp .env $DEPLOYPATH 2>/dev/null || true